# .streamlit/secrets.toml
# KHÔNG COMMIT FILE NÀY LÊN GITHUB! ĐÃ THÊM VÀO .gitignore
GOOGLE_API_KEY="AIzaSyBeHBJ2groDaR95lnaTqH325PTIZNSUQSU"
[database]
type = "postgresql_uri" # Đặt tên type khác để phân biệt nếu muốn
uri = "postgresql://neondb_owner:npg_qIyAS9NOZPx1@ep-gentle-band-a1ej4fbq-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require" # Dán URI từ Neon vào đây
