# .streamlit/secrets.toml
# KHÔNG COMMIT FILE NÀY LÊN GITHUB! ĐÃ THÊM VÀO .gitignore
GOOGLE_API_KEY="AIzaSyBeHBJ2groDaR95lnaTqH325PTIZNSUQSU"
[database]
type = "postgresql_uri" # Đặt tên type khác để phân biệt nếu muốn
uri = "postgresql://neondb_owner:npg_qIyAS9NOZPx1@ep-gentle-band-a1ej4fbq-pooler.ap-southeast-1.aws.neon.tech/tuvanhd?sslmode=require" # Dán URI từ Neon vào đây
[cookie]
name = "trolyhocduong_admin_auth_cookie"  # Tên gợi nhớ cho cookie
# !!! THAY THẾ KEY NÀY BẰNG KEY BÍ MẬT CỦA RIÊNG BẠN (ÍT NHẤT 32 KÝ TỰ) !!!
key = "ThayTheBangMotChuoiBiMatDaiVaNgauNhienCuaBan_1234567890!@#$%^"
expiry_days = 7 # Cookie sẽ hết hạn sau 7 ngày không hoạt động
